add
void main()
{
  sum(2,5);
}
 
// Arrow Syntax
  void sum(int x,int y) => print('sum is ${ x + y}');
sub
void main() 
  {
  sub(2,5);
}
 
// Arrow Syntax
void sub(int x,int y) => print('sub is ${ x - y}');
multiplication
void main() 
  {
  multiply(2,5);
}
 
// Arrow Syntax
void multiply(int x,int y) => print('multiply is ${ x * y}');
division
void main() 
  {
  divide(2,5);
}
 
// Arrow Syntax
void divide(int x,int y) => print('division is ${ x / y}');

